### PR TITLE
Improve sampling interval handling

### PR DESCRIPTION
**Pull request by sradco**
This patch fixes the records collection from ovirt dwh ,since in 4.0 the sampling interval was updated from 60 seconds to 20 seconds.

We will support only 20 or 60 seconds interval in ManageIQ at this point.

Signed-off-by: Shirly Radco <sradco@redhat.com>

### CODE REVIEW

**Comment by sradco** [comment]
@miq_bot add_label darga/yes

**Comment by blomquisg** [comment]
@sradco, a couple of things:

1) Please include a reason for the PR in the [first comment](https://github.com/ManageIQ/ovirt_metrics/pull/13#issue-172651589).

2) Please review the failing tests.

**Comment by Fryguy** [comment]
@sradco You can ignore the style issues since they were already present in the other files.

**Comment by borod108** [comment]
@miq-bot add_label darga

**Pull request merged**
