### PR TITLE
Custom Postgres Adapter for Rails 5 && PG < 9.1

### PR DESCRIPTION
**Pull request by chrisarcand**
Introduces a custom adapter to maintain compatibility to Postgres databases < version 9.1 (Specifically, 8.4) with ActiveRecord 5.x. Rails 5 does not support versions of Postgres < 9.1.

This avoids monkey patching ActiveRecord for the entire application that the gem is added to just for this one bit of functionality while delaying the need to rewrite this gem in a more suitable form (raw SQL, Arel, what have you). 

The adapter is based off of Rails 5 @ abff83e60e9d91975b4788ef9cca388ab2536c10
(Wed Apr 27 13:56:14 2016 +0200)

See commits for individual backwards compatibility changes.

### CODE REVIEW

**Comment by chrisarcand** [comment]
r? @Fryguy

FYI @gtanzillo && @chessbyte

**Comment by gtanzillo** [comment]
@chrisarcand running with your changes in this PR, I enabled C&U collection and I'm seeing rows in my metrics and metric_rollups table 🍻 

Currenty, I'm only seeing data for EmsClusters. I would expect to see VMs and Hosts collected first. Maybe it works differently with RHEVM. I'll keep it running and see what else I get.

**Comment by gtanzillo** [comment]
👍 Both @chrisarcand and I tested this separately with app running C&U collection and we were both successfully able to collect metrics 👏

**Comment by chrisarcand** [comment]
*Note: there's a bug in the auth collection for multi-endpoint stuff that @juliancheal and I are currently fixing.

**Comment by gtanzillo** [comment]
👍 I'm ready to merge this. Do we need to update the version in the Gemfile on ManageIQ/ManageIQ?

**Comment by chrisarcand** [comment]
Yes there are a few things that need doing post-gem-cut.

**Pull request merged**
